name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  eslint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  build-check:
    runs-on: ubuntu-latest
    needs: eslint-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  merge-check:
    runs-on: ubuntu-latest
    needs: [eslint-check, build-check]

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify mergeability
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequest = context.payload.pull_request;
            if (!pullRequest) {
              throw new Error('This action must be run on a pull request.');
            }

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequest.number,
            });

            if (pr.mergeable === false) {
              throw new Error('This pull request cannot be merged.');
            }
